// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovsA0dNt4t4Nb7lV83B_bAR3vlPvplaI',
    appId: '1:240918942404:web:a596b121bc151aee8aef91',
    messagingSenderId: '240918942404',
    projectId: 'sohamdb-4f4e8',
    authDomain: 'sohamdb-4f4e8.firebaseapp.com',
    storageBucket: 'sohamdb-4f4e8.appspot.com',
    measurementId: 'G-C8QJW9RB2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgeDzUOERAozqsdMuT1GdmlwHOEIU6ba8',
    appId: '1:240918942404:android:e2f7957b25403b628aef91',
    messagingSenderId: '240918942404',
    projectId: 'sohamdb-4f4e8',
    storageBucket: 'sohamdb-4f4e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaBot2HXqMahV6yaSl9mizs6RW4ybXeE0',
    appId: '1:240918942404:ios:e6331c26d75402e28aef91',
    messagingSenderId: '240918942404',
    projectId: 'sohamdb-4f4e8',
    storageBucket: 'sohamdb-4f4e8.appspot.com',
    iosBundleId: 'com.example.internAsgnPersist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaBot2HXqMahV6yaSl9mizs6RW4ybXeE0',
    appId: '1:240918942404:ios:5922ae09ef7c164e8aef91',
    messagingSenderId: '240918942404',
    projectId: 'sohamdb-4f4e8',
    storageBucket: 'sohamdb-4f4e8.appspot.com',
    iosBundleId: 'com.example.internAsgnPersist.RunnerTests',
  );
}
